// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coding-tool/AccordionForm.tsx": () => import("../components/mockups/coding-tool/AccordionForm.tsx"),
  "./components/mockups/coding-tool/DenseTriage.tsx": () => import("../components/mockups/coding-tool/DenseTriage.tsx"),
  "./components/mockups/coding-tool/FocusedWizard.tsx": () => import("../components/mockups/coding-tool/FocusedWizard.tsx"),
  "./components/mockups/coding-tool/HeroQuestion.tsx": () => import("../components/mockups/coding-tool/HeroQuestion.tsx"),
  "./components/mockups/coding-tool/HorizontalAnswers.tsx": () => import("../components/mockups/coding-tool/HorizontalAnswers.tsx"),
  "./components/mockups/coding-tool/RightSidebar.tsx": () => import("../components/mockups/coding-tool/RightSidebar.tsx"),
  "./components/mockups/coding-tool/SplitPanel.tsx": () => import("../components/mockups/coding-tool/SplitPanel.tsx"),
  "./components/mockups/coding-tool/TopNavBar.tsx": () => import("../components/mockups/coding-tool/TopNavBar.tsx"),
  "./components/mockups/coding-tool/TriColumn.tsx": () => import("../components/mockups/coding-tool/TriColumn.tsx")
};
