// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/coding-tool/DenseTriage.tsx": () => import("../components/mockups/coding-tool/DenseTriage.tsx"),
  "./components/mockups/coding-tool/FocusedWizard.tsx": () => import("../components/mockups/coding-tool/FocusedWizard.tsx"),
  "./components/mockups/coding-tool/SplitPanel.tsx": () => import("../components/mockups/coding-tool/SplitPanel.tsx")
};
